name: eval

services:
  web:
    build:
      context: ../web
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - assets:/app/assets
    environment:
      - DOCKER_HOST=tcp://sandbox:2375
    depends_on:
      - db
      - sandbox
    networks:
      - app-network

  db:
    image: postgres:15.0
    restart: unless-stopped
    env_file:
      - ./db/.env.db.prod
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  nginx:
    image: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
      - certbot-www:/var/www/certbot
    depends_on:
      - web
    networks:
      - app-network

  sandbox:
    image: docker:28.2.2-dind
    runtime: sysbox-runc
    restart: unless-stopped
    expose:
      - "2375"
    environment:
      - DOCKER_TLS_CERTDIR=
    networks:
      - app-network

  # One-shot certbot container (manual run only)
  certbot:
    image: certbot/certbot
    volumes:
      - ./ssl:/etc/letsencrypt
      - certbot-www:/var/www/certbot
    networks:
      - app-network

volumes:
  pgdata:
  assets:
  certbot-www:

networks:
  app-network:
    driver: bridge
