name: Deploy Dispatch

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Deployment Target? (PROD | STAGE | SECURE | DEMO)'
        required: true
        default: 'DEMO'

jobs:
  deploy_to_prod:
    environment: deployment_env
    runs-on: [self-hosted, prod-runner]
    if: github.event.inputs.target == 'PROD'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to PROD
        uses: ./.github/actions/deploy
        with:
          
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          NEXTAUTH_URL: https://eval.iict-heig-vd.in
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          NEXTAUTH_SWITCH_CLIENT_ID: hes-so_open_didac
          NEXTAUTH_SWITCH_CLIENT_SECRET: ${{ secrets.NEXTAUTH_SWITCH_CLIENT_SECRET }}
          SSL_FULLCHAIN: ${{ secrets.SSL_FULLCHAIN }}
          SSL_PRIVKEY: ${{ secrets.SSL_PRIVKEY }}
          TERMS_OF_SERVICE: ${{ vars.TERMS_OF_SERVICE }}

  deploy_to_stage:
    environment: deployment_env
    runs-on: [self-hosted, stage-runner]
    if: github.event.inputs.target == 'STAGE'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to STAGE
        uses: ./.github/actions/deploy
        with:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          NEXTAUTH_URL: https://eval-staging.iict-heig-vd.in/
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          NEXTAUTH_SWITCH_CLIENT_ID: hes-so_open_didac
          NEXTAUTH_SWITCH_CLIENT_SECRET: ${{ secrets.NEXTAUTH_SWITCH_CLIENT_SECRET }}
          SSL_FULLCHAIN: ${{ secrets.SSL_FULLCHAIN }}
          SSL_PRIVKEY: ${{ secrets.SSL_PRIVKEY }}
          TERMS_OF_SERVICE: ${{ vars.TERMS_OF_SERVICE }}

  deploy_to_secure:
    environment: deployment_env
    runs-on: [self-hosted, secure-runner]
    if: github.event.inputs.target == 'SECURE'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to SECURE
        uses: ./.github/actions/deploy
        with:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          NEXTAUTH_URL: https://eval-secured.iict-heig-vd.in
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          NEXTAUTH_SWITCH_CLIENT_ID: hes-so_open_didac
          NEXTAUTH_SWITCH_CLIENT_SECRET: ${{ secrets.NEXTAUTH_SWITCH_CLIENT_SECRET }}
          SSL_FULLCHAIN: ${{ secrets.SSL_FULLCHAIN }}
          SSL_PRIVKEY: ${{ secrets.SSL_PRIVKEY }}
          TERMS_OF_SERVICE: ${{ vars.TERMS_OF_SERVICE }}

  deploy_to_demo:
    environment: deployment_env
    runs-on: [self-hosted, demo-runner]
    if: github.event.inputs.target == 'DEMO'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to DEMO
        uses: ./.github/actions/deploy
        with:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          NEXTAUTH_URL: https://eval-demo.iict-heig-vd.in
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          NEXTAUTH_SWITCH_CLIENT_ID: hes-so_open_didac
          NEXTAUTH_SWITCH_CLIENT_SECRET: ${{ secrets.NEXTAUTH_SWITCH_CLIENT_SECRET }}
          SSL_FULLCHAIN: ${{ secrets.SSL_FULLCHAIN }}
          SSL_PRIVKEY: ${{ secrets.SSL_PRIVKEY }}
          TERMS_OF_SERVICE: ${{ vars.TERMS_OF_SERVICE }}