name: Deploy Dispatch

on:
  workflow_dispatch:

jobs:
  deploy_to_demo:
    environment: deployment_env
    runs-on: [self-hosted, demo-runner]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to DEMO
        uses: ./.github/actions/deploy
        with:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          NEXTAUTH_URL: https://opendidac.iict-heig-vd.ch/
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          NEXTAUTH_SWITCH_CLIENT_ID: hes-so_open_didac
          NEXTAUTH_SWITCH_CLIENT_SECRET: ${{ secrets.NEXTAUTH_SWITCH_CLIENT_SECRET }}
          TERMS_OF_SERVICE: ${{ vars.TERMS_OF_SERVICE }}